### ISSUE TITLE
Spring characteristics defined by function

### ISSUE THREAD

**Issue by PascalGitz** [AxisVM/pyaxisvm#14]
Hello AxisVM-Team

I would like to implement a spring, which stiffness is defined by a function. The image shows how to do this "by hand". 
![image](https://user-images.githubusercontent.com/115550508/220325896-46e2ff0e-3ca3-4576-b6c4-5d940d5795ce.png)

By reading the COM interface manual I was able to add a spring characteristic, that is defined by a function, but i cannot add function points, as it can be done with the "TimeIncrementFunctions". 

```
federeigenschaften = axtlb.RSpringParam_V161(
    SpringType = axtlb.sptNodal,
    NonLinearity = axtlb.spnlTensionAndCompression,
    NNType = axtlb.spnntNonLinearElastic,
    DOFType = axtlb.spdoftTranslation,
    NLDefType = axtlb.spnldtByFunction
)

_ = axm.SpringParams.Add_V161("X-Richtung", federeigenschaften)

```
Could you guide me, how to do that properly? Eventually I would like to add the spring characteristic to my springs.

**Comment by BALOGHBence** [comment]
This seems like a question, rather than an issue. Anyways, I was informed that the question was answered on other platforms.
